language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - hhvm

before_script:
  - pip install --user codecov
  - composer self-update && composer install --dev

script:
  - ./vendor/bin/phpunit

after_success:
  - codecov
