language: php

php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

before_script:
  - pip install --user codecov
  - composer self-update && composer install --dev

script:
  - ./vendor/bin/phpunit

after_success:
  - codecov
