name: healthcheck

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test (twice, if needed)
        run: make test || make test
      - name: Healthcheck ping
        run: wget https://healthchecks.home.mullie.eu/ping/4062be3a-3426-4f9a-a7db-52ec423df66b -T 10 -t 5 -O /dev/null
